// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_250_coins_in_1_game = "CgkIu86qr5EIEAIQAg"; // <GPGSID>
        public const string leaderboard_distance_leaderboard = "CgkIu86qr5EIEAIQBw"; // <GPGSID>
        public const string achievement_1000_coins_in_1_game = "CgkIu86qr5EIEAIQBQ"; // <GPGSID>
        public const string achievement_100_coins_in_1_game = "CgkIu86qr5EIEAIQAQ"; // <GPGSID>
        public const string achievement_500_coins_in_1_game = "CgkIu86qr5EIEAIQAw"; // <GPGSID>
        public const string leaderboard_coins_leaderboard = "CgkIu86qr5EIEAIQBg"; // <GPGSID>
        public const string achievement_750_coins_in_1_game = "CgkIu86qr5EIEAIQBA"; // <GPGSID>

}

